name: usage_stats_new
description: Query Android Usage Statistics (Configurations, Events, Usage)
version: 2.0.6
homepage: https://github.com/acmonetwork/usage_stats

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    plugin:
      platforms:
        android:
          package: io.github.parassharmaa.usage_stats
          pluginClass : UsageStatsPlugin
